import unittest
from pycdxml import cdxml_styler
import filecmp
from pathlib import Path
import logging

logger = logging.getLogger('pycdxml.cdxml_styler')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.INFO)


class CdxmlStylerTest(unittest.TestCase):

    def test_apply_named_style(self):
        styler = cdxml_styler.CDXMLStyler(style_name="ACS 1996")
        styler.apply_style_to_file(self.test_file, outpath=self.out_file)
        self.assertTrue(filecmp.cmp('files/reference_style.cdxml', self.out_file, shallow=False),
                        "Generated cdxml file does not match expected outcome.")

    def setUp(self):
        self.test_file = 'files/styler_test_input.cdxml'
        self.out_file = 'files/styler_test_out.cdxml'

    def tearDown(self):
        # Delete all files generated by tests
        for p in Path("files").glob("*_out.*"):
            p.unlink()


if __name__ == '__main__':
    unittest.main()